### ISSUE TITLE
Projections rebuild 

### ISSUE THREAD

**Issue by vladimirnani** [johnbywater/eventsourcing#140] opened 2018-02-21 10:08 UTC
I wonder in case of rebuilding all projections is there an easy way for getting all aggregates and rebuild their projections. We do have `repository.get_entity()` no `repository.get_entities()`.

**Comment by johnbywater** [comment] 2018-02-21 14:52
Good point. It would be nice to have a method `record_manager.get_sequence_ids()` which could be used by `repository.get_entities()`. `get_sequence_ids()` could be implemented across all the library's record managers.

The problem is that unless the transaction isolation level is increased from the default ("read committed"), so-called "read skews" will occur when, concurrently with the above operation, new events are also being appended. So probably the better approach is to use upstream notification logs with downstream tracking records committed in the same atomic transaction as the projection records. That should be as reliable as database transactions.

I got a first draft of the "Process" class working this morning. It's a subclass of `SimpleApplication` which functions as a projection, responding to its own notification log, so you can automatically step a set of aggregates through an arbitrary sequence of state transitions. I didn't implement partitioning of notification logs, so a process can scale above the throughput limits of a single sequence, but it seems doable. I'm sure many other will already have arrived at this solution, but I can't find anything online.

**Closed** 2018-04-25 02:08 UTC
